### ISSUE TITLE
360images - clarification needed

### ISSUE THREAD

**Issue by NickPax** [joshmarinacci/webxr-workshops#27]
It is not clear to me what the difference is between "equirectangular" images and "360 images". And are "spherical" images something different again?
Do we use one type of image for the outside of a sphere (equirectangular) and another type for the inside of a sphere (360 images)? (I think so according to the text in the workshop.)
Also, might it be worth mentioning cubemaps?

**Comment by joshmarinacci** [comment]
I was wrong. It's not spherical. it's dual fisheye. I've updated the text to clarify and use an example. thx.
