### ISSUE TITLE
First link

### ISSUE THREAD

**Issue by NickPax** [joshmarinacci/webxr-workshops#3]
When I open the first link I see the rendered HTML on the left and the two fishes image on the right (see screenshot). If you click the two fishes you can then click "Remix on Glitch".

![screen shot 2018-07-24 at 09 57 24](https://user-images.githubusercontent.com/8955802/43124740-4f1038da-8f28-11e8-99e1-d668ecd60bd4.png)

Minor thing but might trip someone up.

**Comment by joshmarinacci** [comment]
I've updated the text to be more clear. Thank you for catching this.

- J
