### ISSUE TITLE
physics - plane, not box, plus added text

### ISSUE THREAD

**Issue by NickPax** [joshmarinacci/webxr-workshops#35]
Replace " Make a translucent box and place it inside of the camera like this. The box should be a static-body" with:

```Make a translucent plane and place it inside of the camera. The plane should be a static-body.```
```Overwrite the original camera script with this:```

```
<a-camera position="0 0 0">
    <a-plane id="paddle"
        width="1.5"
        height="1"
        position="0 0 -1.5"
        static-body
        material="color:pink; transparent:true; opacity:0.5"
   ></a-plane>
</a-camera>
```

**Comment by joshmarinacci** [comment]
Good catch.
