### ISSUE TITLE
Showing how to link to another HTML page + text alterations

### ISSUE THREAD

**Issue by NickPax** [joshmarinacci/webxr-workshops#6]
In this sentence:
"Change the a link to point to rocket.html instead of the nasa website." I suggest showing how to write the link, e.g.` <a href="/rocket.html">moon rocket</a>`

Also I suggest including angle brackets around the 'a' element and formatting it: "Change the `<a>` link ..."
And have NASA be all caps.

**Comment by joshmarinacci** [comment]
fixed. thx.
